pipeline {
  environment {
  }

  agent any

  stages {
    stage("Taking Source Checkout") {
      steps {
	checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'GITHUB', url: 'https://github.com/Deepanshu-Choudhary/sample-project-maven.git']]])

        // environment variables are not masked
        sh 'echo "Code has been successfully checked out from the repo"'
      }
    }
  }
}
