pipeline {
  environment {
    // environment variables and credential retrieval can be interspersed
    SOME_VAR = "SOME VALUE"
    // this assumes that "cred1" has been created on Jenkins Credentials
     CRED1 = credentials("Docker")
  }

  agent any

  stages {
    stage("foo") {
      steps {
        // environment variables are not masked
        echo $Deploy
        sh 'echo "SOME_VAR is $SOME_VAR"'
        sh 'echo "INBETWEEN is $INBETWEEN"'
        sh 'echo $CRED1 > cred1.txt'
      }
    }
  }
  }
